name: test

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm test
        run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: bcrypt_lib-${{ matrix.platform }}
          path: lib/binding/napi-v3/bcrypt_lib.node
